[package]
name = "hip"
version = "0.1.0"
authors = ["Xnuk Shuman <admin@xnu.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hangeul = "0.2.0"
